title: "u-install"
description: "Universal package manager wrapper for Linux — simple and easy"
remote_theme: "just-the-docs/just-the-docs"
url: "https://runvoid.github.io"
baseurl: "/u-install"

search_enabled: true

aux_links:
  "GitHub": "https://github.com/runvoid/u-install"
